import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,makeVoice,normalizeState,roomVoices,counts,selectRooms,toggleFollow,addVoice,setRoomVisibility,removeVoice,escapeHTML,evidenceFamilies} from '../core.mjs';
import {rooms,voices} from '../data.mjs';
const valid=(overrides={})=>({id:'local-test',text:'ข้อมูลสำหรับทดสอบ',kind:'observation',roomId:'canal-demo',includeInRoom:false,createdAt:'2026-09-23T17:00:00+07:00',...overrides});
test('three distinct event cards, not twelve posts',()=>assert.equal(selectRooms(rooms,voices,initialState()).length,3));
test('room count is derived from actual visible voices',()=>assert.deepEqual(counts('canal-demo',voices,initialState()),{voices:6,people:6,local:0}));
test('a new draft is not included in the room',()=>{const s=addVoice(initialState(),valid(),rooms);assert.equal(roomVoices('canal-demo',voices,s).length,6);assert.equal(s.voices.length,1);});
test('draft text cannot affect event search',()=>{const s=addVoice(initialState(),valid({text:'UNIQUE_DRAFT'}),rooms);assert.equal(selectRooms(rooms,voices,s,{query:'UNIQUE_DRAFT'}).length,0);});
test('explicit local room opt-in adds one contribution',()=>{const s=addVoice(initialState(),valid({includeInRoom:true}),rooms);assert.equal(counts('canal-demo',voices,s).voices,7);});
test('two local posts count as one local contributor',()=>{let s=addVoice(initialState(),valid({includeInRoom:true}),rooms);s=addVoice(s,valid({id:'local-two',includeInRoom:true}),rooms);assert.equal(counts('canal-demo',voices,s).people,7);});
test('withdrawal removes voice from room and counts, not original',()=>{const s=setRoomVisibility(addVoice(initialState(),valid({includeInRoom:true}),rooms),'local-test',false);assert.equal(counts('canal-demo',voices,s).voices,6);assert.equal(s.voices.length,1);});
test('deletion removes local original',()=>assert.equal(removeVoice(addVoice(initialState(),valid(),rooms),'local-test').voices.length,0));
test('a contribution in one room does not enter another',()=>{const s=addVoice(initialState(),valid({includeInRoom:true}),rooms);assert.equal(roomVoices('model-demo',voices,s).length,3);});
test('repeated media reference counts as one known family',()=>{assert.equal(rooms[0].evidence.length,3);assert.equal(evidenceFamilies(rooms[0]),2);});
test('following is reversible and unique',()=>{let s=toggleFollow(initialState(),'canal-demo',rooms);assert.deepEqual(s.follows,['canal-demo']);s=toggleFollow(s,'canal-demo',rooms);assert.deepEqual(s.follows,[]);});
test('following filter is honest when empty',()=>assert.equal(selectRooms(rooms,voices,initialState(),{filter:'following'}).length,0));
test('category filter works',()=>assert.deepEqual(selectRooms(rooms,voices,initialState(),{filter:'tech'}).map(r=>r.id),['model-demo']));
test('search finds original public-room text',()=>assert.deepEqual(selectRooms(rooms,voices,initialState(),{query:'ไม่ได้อยู่ในพื้นที่'}).map(r=>r.id),['canal-demo']));
test('empty text is rejected',()=>assert.throws(()=>makeVoice(valid({text:'   '}),rooms)));
test('overlong code-point text is rejected',()=>assert.throws(()=>makeVoice(valid({text:'ก'.repeat(1001)}),rooms)));
test('1000 emoji code points are accepted',()=>assert.equal([...makeVoice(valid({text:'🌊'.repeat(1000)}),rooms).text].length,1000));
test('unknown room is rejected',()=>assert.throws(()=>makeVoice(valid({roomId:'bad'}),rooms)));
test('unknown voice type is rejected',()=>assert.throws(()=>makeVoice(valid({kind:'verified'}),rooms)));
test('boolean opt-in is required, not truthy strings',()=>assert.throws(()=>makeVoice(valid({includeInRoom:'false'}),rooms)));
test('malicious identifier is rejected',()=>assert.throws(()=>makeVoice(valid({id:'x" onclick=bad'}),rooms)));
test('invalid timestamp is rejected',()=>assert.throws(()=>makeVoice(valid({createdAt:'yesterday'}),rooms)));
test('HTML is escaped for user generated text',()=>assert.equal(escapeHTML('<img src=x onerror="1">&'),'&lt;img src=x onerror=&quot;1&quot;&gt;&amp;'));
test('stored author spoofing is discarded',()=>{const s=normalizeState({version:1,voices:[{...valid(),author:'Admin',local:false}],follows:[]},rooms);assert.equal(s.voices[0].author,'คุณ');assert.equal(s.voices[0].local,true);});
test('duplicate IDs are rejected on loading',()=>assert.throws(()=>normalizeState({version:1,voices:[valid(),valid()],follows:[]},rooms)));
test('unknown storage version is not silently accepted',()=>assert.throws(()=>normalizeState({version:2,voices:[],follows:[]},rooms)));
test('invalid and repeated follows are normalized',()=>assert.deepEqual(normalizeState({version:1,voices:[],follows:['no','canal-demo','canal-demo']},rooms).follows,['canal-demo']));
test('new voices do not change manually curated claim states',()=>{const before=JSON.stringify(rooms);addVoice(initialState(),valid({includeInRoom:true}),rooms);assert.equal(JSON.stringify(rooms),before);});
test('every demonstration evidence link resolves to an original voice',()=>{for(const r of rooms){for(const e of r.evidence){assert.ok(voices.some(v=>v.id===e.voice&&v.roomId===r.id));}for(const c of r.claims){for(const ref of c.refs)assert.ok(r.evidence.some(e=>e.id===ref));}}});
test('draft inclusion cannot be changed for an absent local voice',()=>assert.throws(()=>setRoomVisibility(initialState(),'missing',true)));
test('reserved seed IDs cannot be used by local voices',()=>assert.throws(()=>makeVoice(valid({id:'v1'}),rooms)));
test('oversized stored state is rejected, never silently truncated',()=>assert.throws(()=>normalizeState({version:1,voices:Array.from({length:201},(_,i)=>valid({id:'local-'+i})),follows:[]},rooms)));
