"""P2.1c.2d.4c.5b signed account-link proof boundary.

This is intentionally not an HTTP route. The untrusted caller supplies only a
Bearer access token and an empty JSON object. Issuer/subject come only from strict
cryptographic token verification; proof_id is generated by the server; Actor/Source
are generated inside the sealed database function. No durable principal is required
yet, because this boundary exists specifically for first-time account onboarding.
"""
from __future__ import annotations

import base64
import binascii
from dataclasses import dataclass
import re
import time
from typing import Callable
from uuid import UUID, uuid4

import jwt

from identity_boundary import Config, TOKEN_LIMIT, _json_object

ISSUE_SQL = '''SELECT echo_identity.runtime_issue_account_link_proof(
    %s,%s,%s,%s,%s,%s,%s)'''
_MAX_BODY = 256
_MAX_SAFE_MS = 9007199254740991


class SignedAccountLinkError(Exception):
    """Public-safe category only; never include tokens, claims, DSN or DB text."""

    def __init__(self, code: str):
        self.code = code
        super().__init__(code)


@dataclass(frozen=True)
class AccountLinkReceipt:
    proof_id: UUID
    expires_at_ms: int


def _ms(seconds: int) -> int:
    if type(seconds) is not int or seconds < 0 or seconds > _MAX_SAFE_MS // 1000:
        raise ValueError('NumericDate cannot be represented safely')
    return seconds * 1000


def _strict_signed_identity(config: Config, authorization: str | None) -> dict:
    try:
        if type(authorization) is not str or not authorization.startswith('Bearer '):
            raise ValueError('bearer required')
        token = authorization[7:]
        if not 0 < len(token) <= TOKEN_LIMIT:
            raise ValueError('token size')
        parts = token.split('.')
        if len(parts) != 3 or any(not re.fullmatch(r'[A-Za-z0-9_-]+', p) for p in parts):
            raise ValueError('compact JWS required')

        def decode(part: str) -> dict:
            raw = base64.urlsafe_b64decode(part + '=' * (-len(part) % 4))
            return _json_object(raw, TOKEN_LIMIT)

        header = decode(parts[0])
        untrusted = decode(parts[1])
        if (set(header) != {'alg', 'typ', 'kid'} or header['alg'] != 'RS256'
                or header['typ'] != 'at+jwt' or type(header['kid']) is not str
                or header['kid'] not in config.keys):
            raise ValueError('unsupported header')

        claims = jwt.decode(
            token, config.keys[header['kid']], algorithms=['RS256'],
            issuer=config.issuer, audience=config.audience, leeway=0,
            options={'require': ['iss','aud','sub','exp','iat','nbf','jti'],
                     'verify_signature': True, 'verify_exp': True,
                     'verify_nbf': True, 'verify_iat': True,
                     'verify_iss': True, 'verify_aud': True,
                     'verify_sub': True, 'verify_jti': True, 'strict_aud': True},
        )
        if claims != untrusted or claims['iss'] != config.issuer or claims['aud'] != config.audience:
            raise ValueError('claim mismatch')
        if (type(claims['sub']) is not str or not claims['sub'].strip()
                or len(claims['sub']) > 256 or '\x00' in claims['sub']
                or type(claims['jti']) is not str or not claims['jti'].strip()
                or len(claims['jti']) > 256 or '\x00' in claims['jti']):
            raise ValueError('invalid text claim')
        for key in ('iat','nbf','exp'):
            if type(claims[key]) is not int or not 0 <= claims[key] < 2**53:
                raise ValueError('integral NumericDate required')
            _ms(claims[key])
        if not (claims['iat'] <= claims['nbf'] < claims['exp']
                and 0 < claims['exp'] - claims['iat'] <= config.max_lifetime_seconds):
            raise ValueError('invalid validity window')
        return claims
    except (ValueError, TypeError, KeyError, RecursionError, binascii.Error,
            jwt.InvalidTokenError, jwt.InvalidKeyError):
        raise SignedAccountLinkError('IDENTITY_REJECTED') from None


class SignedAccountLinkBoundary:
    """Issue one short-lived DB proof from a verified bearer subject only.

    connect_runtime must provide the trusted transaction-owning pool lease.
    Receipt and final DB time checks occur before leaving that transaction.
    """

    def __init__(self, config: Config, connect_runtime: Callable[[], object]):
        if type(config) is not Config or not callable(connect_runtime):
            raise ValueError('trusted config and runtime connection required')
        self._config = config
        self._connect_runtime = connect_runtime

    def issue(self, authorization: str | None, raw_body: bytes) -> AccountLinkReceipt:
        try:
            body = _json_object(raw_body, _MAX_BODY)
            if body:
                raise ValueError('account-link request accepts no client identity fields')
        except (ValueError, TypeError, KeyError, RecursionError):
            raise SignedAccountLinkError('INVALID_ACCOUNT_LINK_REQUEST') from None

        claims = _strict_signed_identity(self._config, authorization)
        now_ms = int(time.time() * 1000)
        token_exp_ms = _ms(claims['exp'])
        proof_expires_ms = min(token_exp_ms, now_ms + 300_000)
        if proof_expires_ms <= now_ms:
            raise SignedAccountLinkError('IDENTITY_REJECTED')

        proof_id = uuid4()
        params = (
            proof_id, self._config.issuer, claims['sub'],
            _ms(claims['iat']), _ms(claims['nbf']), token_exp_ms, proof_expires_ms,
        )
        try:
            with self._connect_runtime() as c:
                row = c.execute(ISSUE_SQL, params).fetchone()
                # Keep receipt validation INSIDE the transaction: a contract
                # violation must roll back the real proof and any new binding.
                if row is None or len(row) != 1 or type(row[0]) is not dict:
                    raise SignedAccountLinkError('ACCOUNT_LINK_CONTRACT_VIOLATION')
                value = row[0]
                if set(value) != {'proofId','issuer','subject','actorId','sourceId','expiresAtMs','consumed'}:
                    raise SignedAccountLinkError('ACCOUNT_LINK_CONTRACT_VIOLATION')
                try:
                    returned_proof = UUID(value['proofId'])
                    actor_id = UUID(value['actorId'])
                    source_id = UUID(value['sourceId'])
                except (ValueError, TypeError, AttributeError):
                    raise SignedAccountLinkError('ACCOUNT_LINK_CONTRACT_VIOLATION') from None
                if (returned_proof != proof_id or actor_id.int == 0 or source_id.int == 0
                        or actor_id == source_id or value['issuer'] != self._config.issuer
                        or value['subject'] != claims['sub']
                        or value['expiresAtMs'] != proof_expires_ms
                        or value['consumed'] is not False):
                    raise SignedAccountLinkError('ACCOUNT_LINK_CONTRACT_VIOLATION')

                # c5a validates at statement entry, before its advisory lock.
                # Sample the DB wall clock again AFTER that potential wait. The
                # guarantee is this final check, not physical WAL/ack timing.
                clock_row = c.execute('SELECT floor(extract(epoch FROM clock_timestamp())*1000)::bigint').fetchone()
                if (clock_row is None or len(clock_row) != 1
                        or type(clock_row[0]) is not int
                        or not 0 <= clock_row[0] <= _MAX_SAFE_MS):
                    raise SignedAccountLinkError('ACCOUNT_LINK_CONTRACT_VIOLATION')
                checked_ms = clock_row[0]
                if (checked_ms < _ms(claims['iat']) or checked_ms < _ms(claims['nbf'])
                        or checked_ms >= token_exp_ms or checked_ms >= proof_expires_ms):
                    raise SignedAccountLinkError('IDENTITY_REJECTED')
                receipt = AccountLinkReceipt(proof_id=proof_id, expires_at_ms=proof_expires_ms)
        except SignedAccountLinkError:
            raise
        except Exception:
            # Includes unknown commit/reset outcomes. Do not replay automatically
            # or claim a rollback when commit acknowledgement is unavailable.
            raise SignedAccountLinkError('ACCOUNT_LINK_BACKEND_UNAVAILABLE') from None

        # A result is released only after the pool's commit and reset succeed.
        return receipt
