import test from 'node:test';
import assert from 'node:assert/strict';
import { ROOMS, VOICES } from '../data.js';
import { escapeHTML,safeURL,emptyStore,normalizeStore,allRooms,roomVoices,roomStats,groups,getClaimState,filterRooms,makeVoice,makeRoom,removeVoice,toggleFollow } from '../core.js';
const input={roomId:'canal-demo',name:'ผู้ทดลอง',kind:'observation',text:'ข้อความทดลอง',shared:true};
const local=(overrides={},id='test-01')=>makeVoice({...input,...overrides},emptyStore(),id,1727080200000);
test('fixtures have unique room and voice identities',()=>{assert.equal(new Set(ROOMS.map(x=>x.id)).size,ROOMS.length);assert.equal(new Set(VOICES.map(x=>x.id)).size,VOICES.length)});
test('fixture voices all refer to known rooms',()=>assert.ok(VOICES.every(v=>ROOMS.some(r=>r.id===v.roomId))));
test('claims reference original voices in the SAME room',()=>{for(const r of ROOMS)for(const c of r.claims)for(const id of [...c.support,...c.counter])assert.ok(VOICES.some(v=>v.id===id&&v.roomId===r.id))});
test('one card per event, not per voice',()=>assert.equal(filterRooms(emptyStore()).length,4));
test('reposted evidence keeps one family',()=>{const s=roomStats('canal-demo',emptyStore());assert.equal(s.voices,6);assert.equal(s.families,3)});
test('support, counter and unknown are separate fixture labels',()=>assert.deepEqual(ROOMS[0].claims.map(c=>getClaimState(c,emptyStore()).status),['SUPPORTED','DISPUTED','UNKNOWN']));
test('new local observations never auto-approve claim evidence',()=>{let s=emptyStore();for(let n=0;n<100;n++)s.voices.push(local({},'v'+n));assert.equal(getClaimState(ROOMS[0].claims[1],s).status,'DISPUTED');assert.equal(roomStats('canal-demo',s).pending,100)});
test('question cannot silently become a verified fact',()=>{const s=emptyStore();s.voices.push(local({kind:'question'}));assert.equal(getClaimState(ROOMS[0].claims[2],s).status,'UNKNOWN')});
test('private local voice is absent from room view and counts',()=>{const s=emptyStore();s.voices.push(local({shared:false}));assert.equal(roomVoices('canal-demo',s).length,6);assert.equal(roomStats('canal-demo',s).pending,0)});
test('private text is absent from event search',()=>{const s=emptyStore();s.voices.push(local({shared:false,text:'private-secret-needle'}));assert.equal(filterRooms(s,{query:'private-secret-needle'}).length,0)});
test('shared local text appears in appropriate event search',()=>{const s=emptyStore();s.voices.push(local({text:'unique-search-needle'}));assert.equal(filterRooms(s,{query:'unique-search-needle'})[0].id,'canal-demo')});
test('group totals equal visible voices',()=>assert.equal(groups('canal-demo',emptyStore()).reduce((n,g)=>n+g.voices.length,0),6));
test('follow toggle persists a single room identity',()=>{let s=toggleFollow(emptyStore(),'canal-demo');assert.deepEqual(s.following,['canal-demo']);s=toggleFollow(s,'canal-demo');assert.equal(s.following.length,0)});
test('unknown follow target is ignored',()=>assert.deepEqual(toggleFollow(emptyStore(),'missing'),emptyStore()));
test('remove voice removes it from every rendered room projection',()=>{let s=emptyStore();const v=local();s.voices.push(v);s=removeVoice(s,v.id);assert.equal(roomStats('canal-demo',s).voices,6);assert.equal(s.voices.length,0)});
test('HTML metacharacters are escaped, not treated as markup',()=>assert.equal(escapeHTML('<img onerror="x"> & \' '),'&lt;img onerror=&quot;x&quot;&gt; &amp; &#39; '));
test('unsafe schemes are rejected',()=>{for(const x of ['javascript:alert(1)','data:text/html,abc','file:///etc/passwd','ftp://example.com','not-a-url'])assert.equal(safeURL(x),'')});
test('https links remain usable',()=>assert.equal(safeURL('https://example.com/source'),'https://example.com/source'));
test('invalid text, type and room are rejected',()=>{assert.throws(()=>local({text:''}));assert.throws(()=>local({text:'x'.repeat(2001)}));assert.throws(()=>local({kind:'verified'}));assert.throws(()=>local({roomId:'missing'}))});
test('bad link and duplicate ID are rejected',()=>{assert.throws(()=>local({link:'javascript:alert(1)'}));const s=emptyStore();s.voices.push(local());assert.throws(()=>makeVoice(input,s,'test-01'))});
test('new room is local, has no invented accepted claims',()=>{const r=makeRoom('ห้องใหม่','พื้นที่และชุมชน','room01',emptyStore());assert.equal(r.local,true);assert.equal(r.claims.length,0)});
test('local room and voice survive validated store roundtrip',()=>{const s=emptyStore();const r=makeRoom('ห้องใหม่','พื้นที่และชุมชน','r',s);s.rooms.push(r);s.voices.push(makeVoice({...input,roomId:r.id},s,'vv'));const restored=normalizeStore(JSON.parse(JSON.stringify(s)));assert.equal(restored.rooms.length,1);assert.equal(roomVoices(r.id,restored).length,1)});
test('tampered local storage cannot inject accepted evidence',()=>{const v=local();v.evidence={id:'fake',family:'fake'};const s=normalizeStore({version:1,voices:[v],rooms:[],following:[]});assert.equal(s.voices[0].evidence,undefined)});
test('malformed storage falls back without crashing',()=>{for(const x of [null,[],42,{version:9},{version:1,voices:[null,{},'abc'],rooms:[null],following:[null]}])assert.deepEqual(normalizeStore(x),emptyStore())});
test('unsafe room IDs and forged visibility are discarded or private',()=>{const v=local();v.shared='true';const s=normalizeStore({version:1,voices:[v],rooms:[{id:'<img>',title:'x'}],following:['missing']});assert.equal(s.rooms.length,0);assert.equal(s.voices[0].shared,false);assert.equal(s.following.length,0)});
test('local author is counted once across posts',()=>{const s=emptyStore();s.voices.push(local({name:'A'},'one'),local({name:'B'},'two'));assert.equal(roomStats('canal-demo',s).people,7)});
test('topic filter only returns matching category',()=>assert.ok(filterRooms(emptyStore(),{topic:'เทคโนโลยี'}).every(r=>r.category==='เทคโนโลยี')));
test('no freshness is invented from a recent repost',()=>{const s=emptyStore();s.voices.push(local());assert.equal(getClaimState(ROOMS[0].claims[0],s).freshness,'UNKNOWN')});
