import {renderFeedCard} from './feed-v2.mjs';
import {createEvidenceInspector} from './evidence-inspector.mjs';
import {renderRoomV2, mountRoomV2} from './room-v2.mjs';
import {VERSION,STORE_KEY,TYPES,escapeHTML as esc,initialState,normalizeState,roomVoices,counts,selectRooms,toggleFollow,addVoice,setRoomVisibility,removeVoice,evidenceFamilies} from './core.mjs';
import {rooms,voices,stateNames} from './data.mjs';
const app=document.querySelector('#app'), modal=document.querySelector('#modal');
let unmountRoom=()=>{}, modalReturnFocus=null;
let state=initialState(), storageWarning='', query='', filter='all', roomLayer='reality', kindFilter='all', currentRoom=null, lastRoute='', toastTimer;
try { const saved=localStorage.getItem(STORE_KEY); if(saved) state=normalizeState(JSON.parse(saved),rooms); }
catch { storageWarning='อ่านข้อมูลทดลองเดิมไม่ได้ จึงเปิดแบบไม่ใช้ข้อมูลนั้น ข้อมูลเดิมยังไม่ถูกเขียนทับ'; }
const icons={feed:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',follow:'M12 3v18M3 12h18',user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21v-2a8 8 0 0 1 16 0v2',info:'M12 17v-5M12 8h.01M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',back:'M19 12H5M12 5l-7 7 7 7'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name]||icons.info}"/></svg>`;
const brand=cls=>`<a class="brand ${cls||''}" href="#/" aria-label="Echo News หน้าแรก"><img src="./icon.svg" alt="">echo<span>.</span></a>`;
function notify(message){ const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),4500); }
function persist(next){ if(storageWarning) throw Error('ข้อมูลเก่ายังมีปัญหา ไปหน้าเกี่ยวกับเพื่อล้างข้อมูลทดลองก่อนบันทึก');try{localStorage.setItem(STORE_KEY,JSON.stringify(next));}catch{throw Error('บันทึกในเบราว์เซอร์ไม่สำเร็จ ข้อมูลใหม่ยังไม่ถูกบันทึก');}state=next; }
const nav=(route,mobile=false)=>[['/','feed','ฟีดห้องข่าว'],['/following','follow','ที่ติดตาม'],['/me','user','เสียงของฉัน'],['/about','info','เกี่ยวกับ']].map(([path,i,title],idx)=>`${mobile&&idx===2?'<button data-action="compose" aria-label="สร้างเสียงใหม่">+</button>':''}<a class="${mobile?'':'navlink '}${route===path?'active':''}" href="#${path}" ${route===path?'aria-current="page"':''}>${icon(i)}${title}</a>`).join('');
function shell(route){app.innerHTML=`<aside class="sidebar">${brand()}<div><p class="eyebrow">NEWS, WITH EVERY VOICE.</p><p class="small muted">หนึ่งเหตุการณ์ หลายเสียง</p></div><nav aria-label="เมนูหลัก">${nav(route)}</nav><button class="primary" data-action="compose">+ เพิ่ม Echo Voice</button><div class="foot">RESEARCH PREVIEW ${VERSION}<br>ข้อมูลตัวอย่าง ไม่ใช่ข่าวสด<br>ไม่มี AI ตรวจข่าวอัตโนมัติ</div></aside><div class="shell"><header class="topbar">${brand('mobilebrand')}<label class="search">${icon('search')}<input id="search" type="search" placeholder="ค้นหาเหตุการณ์หรือเสียงในห้อง" aria-label="ค้นหาเหตุการณ์หรือเสียงในห้อง" value="${esc(query)}"></label><div class="topmeta"><span class="badge">◌ RESEARCH PREVIEW</span><a href="#/me" class="avatar" aria-label="เสียงของฉัน">ฉัน</a></div></header><div class="notice">${currentRoom||['/','/following'].includes(route)?'<strong>ต้นแบบ • ข้อมูลจำลอง</strong> <span>บันทึกเฉพาะเครื่องนี้</span><a href="#/about">รายละเอียด</a>':'<strong>ต้นแบบ • ข้อมูลจำลอง</strong> บุคคล สถานที่ และหลักฐานในชุดเริ่มต้นเป็นเรื่องสมมติ โพสต์ที่คุณเพิ่มเก็บเฉพาะเบราว์เซอร์นี้ ไม่เผยแพร่ให้ผู้อื่น'}${storageWarning?`<p class="error">${esc(storageWarning)}</p>`:''}</div><div class="layout"><main id="main" tabindex="-1"></main><aside id="rail" class="rail" aria-label="ข้อมูลเพิ่มเติม"></aside></div></div><nav class="bottomnav" aria-label="เมนูมือถือ">${nav(route,true)}</nav>`;}
function routeNow(){return (location.hash.slice(1)||'/').split('?')[0];}
function rail(){document.querySelector('#rail').innerHTML=`<section class="railcard"><span class="raillabel">THE ECHO PRINCIPLE</span><h3>ข่าวหนึ่งเรื่อง<br>ไม่จำเป็นต้องมีเสียงเดียว</h3><div class="orbit" aria-hidden="true"><span class="orbcenter">e</span><span class="satellite s1">ก</span><span class="satellite s2">ข</span><span class="satellite s3">ค</span></div><p>คนโพสต์ในฟีดของตัวเอง<br>ห้องข่าวเชื่อมเสียงที่เกี่ยวข้อง<br>ไม่ลบต้นทาง ไม่เปลี่ยนเจ้าของ</p></section><section class="railcard"><span class="raillabel">EXPLORE ROOMS</span><h3>ห้องในโลกจำลอง</h3>${rooms.map(r=>`<a class="railrow" href="#/room/${r.id}"><span>${esc(r.tag)}</span><span class="lime">${counts(r.id,voices,state).voices} เสียง ↗</span></a>`).join('')}</section><section class="railcard"><span class="raillabel">TRUST BY DESIGN</span><h3>เสียงดัง ≠ ข้อเท็จจริง</h3><p>จำนวนโพสต์ไม่เปลี่ยนป้ายหลักฐาน ป้ายในรุ่นนี้กำหนดจากชุดข้อมูลสาธิต ยังไม่ได้เชื่อมตัวคำนวณฐานข้อมูล</p><a class="textbutton" href="#/about">ดูขอบเขตต้นแบบ ↗</a></section>`;}
function feedCard(r){return renderFeedCard({room:r,counts:counts(r.id,voices,state),followed:state.follows.includes(r.id)});}
function feedPage(following=false){const selected=following?'following':filter;const filtered=selectRooms(rooms,voices,state,{query,filter:selected});return `<section class="intro"><div><p class="eyebrow">ECHO NEWS CENTER</p><h1>${following?'ห้องที่คุณติดตาม':'ห้องข่าว'}</h1><p>${following?'เลือกห้องไว้ กลับมาดูได้ในเบราว์เซอร์นี้':'เห็นสิ่งที่รู้ และยังไม่รู้ ก่อนเข้าห้อง'}</p></div><div class="pulse" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></section>${following?'':`<div class="chips" aria-label="กรองห้อง">${[['all','ทั้งหมด'],['following','ที่ติดตาม'],['community','ชุมชน'],['tech','เทคโนโลยี']].map(([v,t])=>`<button class="chip" data-action="filter" data-value="${v}" aria-pressed="${filter===v}">${t}</button>`).join('')}</div>`}<p class="small muted" id="result-count">${filtered.length} ห้อง · ชุดข้อมูลจำลอง ไม่ใช่ผลสำรวจประชาชน</p><div class="feed">${filtered.map(feedCard).join('')||`<div class="empty"><h3>ยังไม่พบห้อง</h3><p>ลองเปลี่ยนคำค้น หรือเลือกติดตามห้องจากฟีด</p><button class="ghost" data-action="clear-search">ดูทุกห้อง</button></div>`}</div>`;}
function claimCard(c){return `<div class="claim"><div class="claimline"><i class="dot ${c.state.toLowerCase()}" aria-hidden="true"></i><div><span class="state ${c.state.toLowerCase()}">${stateNames[c.state]} · ป้ายจากข้อมูลสาธิต</span><p>${esc(c.text)}</p></div></div><p class="small">${esc(c.fresh)}</p><button class="textbutton" data-action="claim" data-id="${c.id}">ดูเหตุผลและต้นทาง ${c.refs.length} รายการ ↗</button></div>`;}
function voiceCard(v,owner=false){const room=rooms.find(r=>r.id===v.roomId);return `<article class="voicecard" id="voice-${esc(v.id)}"><header class="voicehead"><span class="avatar ${v.kind==='question'?'alt':''}" aria-hidden="true">${esc([...v.author][0])}</span><div><span class="by">${esc(v.author)}</span> <span class="kind">${TYPES[v.kind]}</span><div class="small muted">${v.local?'บันทึกบนเครื่องนี้เท่านั้น':'บัญชีจำลอง · @'+esc(v.handle)}</div></div><span class="when">${v.local?'โพสต์ของคุณ':esc(v.time)}</span></header><p class="voicecontent">${esc(v.text)}</p>${v.repostOf?'<p class="repost">↳ อ้างรายงานเดิม ไม่ใช่หลักฐานต้นทางใหม่</p>':''}<footer class="voicetools"><button data-action="original" data-id="${esc(v.id)}">↗ ดูโพสต์ต้นฉบับ</button>${owner?`<a href="#/room/${v.roomId}">${esc(room.tag)} · ${v.includeInRoom?'แสดงในห้องบนเครื่องนี้':'ฉบับร่าง ไม่รวมห้อง'}</a><button data-action="visibility" data-id="${esc(v.id)}">${v.includeInRoom?'ถอนออกจากห้อง':'นำเข้าห้องในเครื่อง'}</button><button data-action="delete" data-id="${esc(v.id)}">ลบจากเครื่อง</button>`:''}</footer></article>`;}
function evidenceCard(e){return `<article class="card evidencecard"><span class="badge">${esc(e.family)} · หลักฐานจำลอง</span><h3>${esc(e.title)}</h3><p>${esc(e.note)}</p><p>เวลาในตัวอย่าง ${esc(e.when)} · ยังไม่ได้ประเมินความเป็นอิสระ</p><button class="textbutton" data-action="evidence" data-id="${esc(e.id)}">รายละเอียดหลักฐาน →</button><button class="textbutton" data-action="original" data-id="${e.voice}">เปิดเสียงต้นทาง ↗</button></article>`;}
function roomPage(r){return renderRoomV2({room:r,voices:roomVoices(r.id,voices,state),counts:counts(r.id,voices,state),followed:state.follows.includes(r.id),layer:roomLayer,kindFilter,claimCard,voiceCard,evidenceCard});}
function mePage(){return `<section class="profilehero"><span class="avatar">ฉัน</span><p class="eyebrow">YOUR ORIGINAL VOICES</p><h1>เสียงของฉัน</h1><p>ไม่ใช่บัญชีออนไลน์ ไม่มีการส่งข้อมูลไปเซิร์ฟเวอร์<br>ข้อมูลในเบราว์เซอร์ไม่เข้ารหัส ผู้ใช้อุปกรณ์เดียวกันอาจเข้าถึงได้</p></section><button class="primary" data-action="compose">+ เขียนเสียงใหม่</button><div class="info">${state.voices.length} โพสต์ในเครื่อง · ${state.voices.filter(v=>v.includeInRoom).length} โพสต์เชื่อมกับห้อง<br><span class="muted">การนำเข้าห้องเป็นเพียงการเปลี่ยนมุมมองบนเครื่องนี้</span></div>${state.voices.length?[...state.voices].reverse().map(v=>voiceCard(v,true)).join(''):'<div class="empty"><h3>พื้นที่สำหรับเสียงของคุณ</h3><p>ลองเขียนโพสต์หนึ่งชิ้น แล้วดูว่ามันเชื่อมเข้าห้องข่าวอย่างไร</p></div>'}`;}
function aboutPage(){return `<p class="eyebrow">RESEARCH, NOT A CLAIM OF TRUTH</p><h1 class="roomtitle">Echo News Center</h1><p class="muted">หนึ่งเหตุการณ์ หลายเสียง<br>เก็บต้นทางไว้ ไม่หลอมทุกคนเป็นคำตอบเดียว</p><section class="info"><h3>รุ่น ${VERSION} · ต้นแบบหน้าจอ</h3><p>ฟีดเหตุการณ์ ห้องรวมเสียง โพสต์ต้นฉบับ การติดตามห้อง และการบันทึกเฉพาะเบราว์เซอร์ทำงานได้ ไม่มี backend, API, login หรือ LLM ทำงานอยู่เบื้องหลัง</p></section><section class="info"><h3>อะไรเป็นข้อมูลจำลอง?</h3><p>ทุกเหตุการณ์ บุคคล สถานที่ ข้อความตัวอย่าง หลักฐาน และป้ายสถานะในชุดเริ่มต้นเป็นเรื่องสมมติ แผนภาพสีไม่ใช่ภาพถ่ายหลักฐาน และใช้ประกอบ UI เท่านั้น ห้ามใช้ตัดสินใจในเหตุฉุกเฉิน</p></section><section class="info"><h3>ข้อมูลของคุณอยู่ที่ไหน?</h3><p>โพสต์และรายการห้องที่ติดตามเก็บใน localStorage ของเบราว์เซอร์นี้ ไม่ซิงก์ข้ามเครื่อง ไม่ส่งถึงผู้ใช้คนอื่น ไม่ใช่พื้นที่เก็บข้อมูลลับ เลือกไม่เข้าห้องได้ และถอนหรือลบได้จากเสียงของฉัน</p></section><section class="info"><h3>ประตูตรวจงานที่ยังไม่ผ่าน</h3><div class="statusrow"><span>P2.1b PostgreSQL runtime</span><span class="muted">UNKNOWN</span></div><div class="statusrow"><span>สิทธิ์ผู้ใช้ / ผู้ตรวจ / ข้อมูลส่วนตัวบนเซิร์ฟเวอร์</span><span class="muted">ยังไม่ทำ</span></div><div class="statusrow"><span>AI จับคู่ Event / ประเมินหลักฐานจริง</span><span class="muted">ยังไม่ทำ</span></div><p>หน้าทดลองนี้ไม่ได้ทำให้ข้อที่ยัง UNKNOWN ผ่าน และไม่ได้เชื่อมฐานข้อมูลอ้างอิง P1.5/P2.1 เข้ามาใช้งาน</p></section><section class="info"><h3>ล้างข้อมูลทดลอง</h3><p>ลบเฉพาะโพสต์และรายการติดตามในเบราว์เซอร์นี้ ไม่ลบชุดตัวอย่าง ไม่ล้างข้อมูลเว็บไซต์อื่น และไม่รับประกันการลบสำเนาใน backup ของอุปกรณ์</p><button class="ghost danger" data-action="reset">ล้างข้อมูลในเครื่อง</button></section>`;}
function render(keepScroll=false){const focus=document.activeElement?.dataset;unmountRoom();const route=routeNow(),changed=lastRoute!==route;if(changed){roomLayer='reality';kindFilter='all';}currentRoom=route.startsWith('/room/')?rooms.find(r=>r.id===route.slice(6)):null;app.classList.toggle('room-mode',Boolean(currentRoom));app.classList.toggle('feed-mode',['/','/following'].includes(route));shell(route);const main=document.querySelector('#main');if(route==='/') main.innerHTML=feedPage();else if(route==='/following') main.innerHTML=feedPage(true);else if(route==='/me') main.innerHTML=mePage();else if(route==='/about') main.innerHTML=aboutPage();else if(currentRoom) main.innerHTML=roomPage(currentRoom);else main.innerHTML='<div class="empty"><h1>ไม่พบห้องนี้</h1><p>ลิงก์อาจไม่ตรงกับชุดข้อมูลต้นแบบ</p><a class="enter" href="#/">กลับหน้าแรก ↗</a></div>';rail();if(currentRoom){unmountRoom=mountRoomV2(main,{onLayerChange:key=>{roomLayer=key;}});}if(keepScroll&&focus?.action){const selector=`[data-action="${CSS.escape(focus.action)}"]${focus.value?`[data-value="${CSS.escape(focus.value)}"]`:''}${focus.room?`[data-room="${CSS.escape(focus.room)}"]`:''}`;[...main.querySelectorAll(selector)].find(el=>el.getClientRects().length)?.focus({preventScroll:true});}document.title=currentRoom?`${currentRoom.title.replace('\n',' ')} · echo.`:'echo. — Echo News Center';lastRoute=route;if(changed&&!keepScroll){window.scrollTo(0,0);main.focus({preventScroll:true});}}
function showModal(title,body){if(!modal.open)modalReturnFocus=document.activeElement;modal.innerHTML=`<div class="modalhead"><h2 id="modal-title">${title}</h2><button class="close" data-action="close" aria-label="ปิดหน้าต่าง">×</button></div>${body}`;if(!modal.open)modal.showModal();}
function compose(roomId){showModal('เพิ่ม Echo Voice',`<p class="small muted">คุณเขียนต้นฉบับ ห้องข่าวเป็นเพียงที่รวมเสียง<br>ไม่มีการโพสต์ออนไลน์ในรุ่นนี้</p><form id="voice-form"><label class="field" for="voice-text">คุณพบอะไร หรือกำลังสงสัยอะไร?</label><textarea id="voice-text" name="text" placeholder="เล่าสิ่งที่คุณเห็น แยกจากสิ่งที่คุณคาดเดา…" required></textarea><p class="small muted" id="char-count">0 / 1,000 ตัวอักษร</p><label class="field" for="voice-kind">ประเภทของเสียง — คุณเลือกเอง ไม่ใช่ AI ตัดสิน</label><select id="voice-kind" name="kind">${Object.entries(TYPES).map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select><label class="field" for="voice-room">ห้องที่เกี่ยวข้อง — เลือกด้วยตนเองในต้นแบบ</label><select id="voice-room" name="roomId">${rooms.map(r=>`<option value="${r.id}" ${(roomId||currentRoom?.id)===r.id?'selected':''}>${esc(r.title.replace('\n',' '))}</option>`).join('')}</select><label class="check"><input type="checkbox" name="include" id="include-room"><span>นำเสียงนี้เข้า Room บนเครื่องนี้ด้วย<br><span class="muted small">ไม่เลือก = เก็บเป็นฉบับร่างในเสียงของฉัน</span></span></label><p id="form-error" class="error" role="alert"></p><div class="formfoot"><p>เก็บเฉพาะเบราว์เซอร์นี้ ไม่เข้ารหัส<br>อย่าใส่ข้อมูลส่วนตัวหรือข้อมูลลับ</p><button type="submit" class="primary">บันทึกในเครื่อง</button></div></form>`);document.querySelector('#voice-text').focus();}
const inspector=createEvidenceInspector({dialog:modal,rooms,getVoices:()=>[...voices,...state.voices],showModal});
function original(id){inspector.openVoice(id);}
document.addEventListener('click',async event=>{const button=event.target.closest('[data-action]');if(!button)return;const a=button.dataset.action;try{
 if(a==='close'){modal.close();return;}
 if(a==='compose'){compose(button.dataset.room);return;}
 if(a==='follow'){persist(toggleFollow(state,button.dataset.room,rooms));render(true);notify('บันทึกการติดตามบนเครื่องนี้แล้ว');return;}
 if(a==='filter'){filter=button.dataset.value;render(true);return;}
 if(a==='clear-search'){query='';filter='all';location.hash='/';render();return;}
 if(a==='kind'){kindFilter=kindFilter===button.dataset.value?'all':button.dataset.value;roomLayer='society';render(true);return;}
 if(a==='feed-claim'){const r=rooms.find(r=>r.id===button.dataset.room);if(r?.claims.some(c=>c.id===button.dataset.id))inspector.openClaim(r.id,button.dataset.id);return;}
 if(a==='original'){original(button.dataset.id);return;}
 if(a==='claim'&&currentRoom){inspector.openClaim(currentRoom.id,button.dataset.id);return;}
 if(a==='evidence'&&currentRoom){inspector.openEvidence(currentRoom.id,button.dataset.id);return;}
 if(a==='share'){const url=location.href.split('#')[0]+'#/room/'+button.dataset.room;try{await navigator.clipboard.writeText(url);notify('คัดลอกลิงก์ห้องแล้ว — ไม่รวมโพสต์ที่เก็บในเครื่อง');}catch{showModal('ลิงก์ห้อง',`<p class="permalink">${esc(url)}</p><p class="small muted">คัดลอกข้อความนี้ ลิงก์ไม่รวมโพสต์ส่วนตัวในเครื่อง</p>`);}return;}
 if(a==='visibility'){const v=state.voices.find(x=>x.id===button.dataset.id);persist(setRoomVisibility(state,v.id,!v.includeInRoom));render(true);notify(v.includeInRoom?'ถอนออกจากห้องแล้ว ต้นฉบับยังอยู่ในเสียงของฉัน':'นำเข้า Room บนเครื่องนี้แล้ว');return;}
 if(a==='delete'){if(!confirm('ลบโพสต์นี้จากเบราว์เซอร์นี้?'))return;persist(removeVoice(state,button.dataset.id));render(true);notify('ลบโพสต์จากข้อมูลแอปบนเครื่องแล้ว');return;}
 if(a==='reset'){if(!confirm('ลบโพสต์และรายการติดตามทั้งหมดของ Echo ในเบราว์เซอร์นี้?'))return;localStorage.removeItem(STORE_KEY);state=initialState();storageWarning='';render();notify('ล้างข้อมูลทดลองของ Echo แล้ว');return;}
 }catch(error){notify(error.message);}});
document.addEventListener('input',event=>{if(event.target.id==='search'){query=event.target.value;if(!['/','/following'].includes(routeNow())){location.hash='/';return;}document.querySelector('#main').innerHTML=feedPage(routeNow()==='/following');}if(event.target.id==='voice-text')document.querySelector('#char-count').textContent=`${[...event.target.value.trim()].length} / 1,000 ตัวอักษร`;});
document.addEventListener('submit',event=>{if(event.target.id!=='voice-form')return;event.preventDefault();const form=new FormData(event.target);try{const input={id:'local-'+crypto.randomUUID(),text:form.get('text'),kind:form.get('kind'),roomId:form.get('roomId'),includeInRoom:form.has('include'),createdAt:new Date().toISOString()};persist(addVoice(state,input,rooms));modal.close();roomLayer='reality';kindFilter='all';location.hash=input.includeInRoom?'/room/'+input.roomId:'/me';render();if(input.includeInRoom)document.querySelector('#room-tab-society')?.click();notify(input.includeInRoom?'บันทึกต้นฉบับและเชื่อมเข้าห้องบนเครื่องนี้แล้ว':'บันทึกฉบับร่าง ไม่ได้นำเข้าห้อง');}catch(error){document.querySelector('#form-error').textContent=error.message;}});
modal.addEventListener('close',()=>{if(modalReturnFocus?.isConnected)modalReturnFocus.focus({preventScroll:true});});
window.addEventListener('hashchange',()=>{if(modal.open)modal.close();render();});
window.addEventListener('storage',event=>{if(event.key!==STORE_KEY&&event.key!==null)return;try{state=event.newValue?normalizeState(JSON.parse(event.newValue),rooms):initialState();storageWarning='';render(true);}catch{notify('ข้อมูลจากอีกแท็บไม่ถูกต้อง ไม่ได้นำมาใช้');}});
window.addEventListener('error',()=>notify('มีข้อผิดพลาดบนหน้าจอ ลองเปิดหน้าใหม่ ข้อมูลยังเก็บในเบราว์เซอร์'));
render();
